CLUSTAL multiple sequence alignment by MUSCLE (3.8)


Pteropus        -----------------------------------MAVRLPAMAAGGSDLRAGDVEEDAS
Sus             MWGPAQPYSDSALSPKPRPFRAVFRGSALPFPAVRVEVRGRSMAAGGSDPRAGDVEEDAS
Homo            ------------------------------------------MAAGGSDPRAGDVEEDAS
Rattus          ------------------------------------------MAAGGSDPRAGDVEEDAS
Otolemur        ------------------------------------------MAAGGSDPRAGDVEEDAS
Chicken         ------------------------------------------MAAGGSDPRTADVEEDAS
Vombatus        ------------------------------------------MAAGGGDPRAGDVEEDAS
                                                          *****.* *:.*******

Pteropus        QLIFPKEFETAETLLNSEVHMLLEHRKQQNESAEDEQELSEVFMKTLNYTARFSRFKNRE
Sus             QLIFPKEFETAETLLNSEVHMLLEHRKQQNESAEDEQELSEVFMKTLNYTARFSRFKNRE
Homo            QLIFPKEFETAETLLNSEVHMLLEHRKQQNESAEDEQELSEVFMKTLNYTARFSRFKNRE
Rattus          QLIFPKEFETAETLLNSEVHMLLEHRKQQNESAEDEQELSEVFMKTLNYTARFSRFKNRE
Otolemur        QLIFPKEFETAETLLNSEVHMLLEHRKQQNESAEDEQELSEVFMKTLNYTSRFSRFKNRE
Chicken         QLVFPKEFETAETLLNSEVHMLLEHRKQQNESAEDEQELSEVFMKTLNYTARFSRFKNRE
Vombatus        QLVFPKEFETAETLLNSEVHMLLEHRKQQNESAEDEQELSEVFMKTLNYTARFSRFKNRE
                **:***********************************************:*********

Pteropus        TIASVRSLLLQKKLHKFELACLANLCPETAEESKALIPSLEGRFEDEELQQILDDIQTKR
Sus             TIASVRSLLLQKKLHKFELACLANLCPETAEESKALIPSLEGRFEDEELQQILDDIQTKR
Homo            TIASVRSLLLQKKLHKFELACLANLCPETAEESKALIPSLEGRFEDEELQQILDDIQTKR
Rattus          TIASVRSLLLQKKLHKFELACLANLCPETAEESKALIPSLEGRFEDEELQQILDDIQTKR
Otolemur        TIASVRSLLLQKKLHKFELACLANLCPETAEESKALIPSLEGRFEDEELQQILDDIQTKR
Chicken         TIASVRSLLLQKKLHKFELACLANLCPETAEEAKALIPSLEGRFEDEELQQILDDIQTKR
Vombatus        TIASVRSLLLQKKLHKFELACLANLCPETAEEAKALIPSLEGRFEDEELQQILDDIQTKR
                ********************************:***************************

Pteropus        SFQY
Sus             SFQY
Homo            SFQY
Rattus          SFQY
Otolemur        SFQY
Chicken         SFQY
Vombatus        SFQY
                ****
