theme: jekyll-theme-minimal
logo: https://www.researchgate.net/publication/273320579/figure/fig3/AS:351390573580289@1460789449730/Schematic-diagram-of-Enigma-machine-from-Scheribus-1928.png
show_downloads: true
title: Bioinformatics
